### ISSUE TITLE
Support "UNTITLED (WORKSPACE)" 

### ISSUE THREAD

**Issue by GloobyBoolga** [JScearcy/rust-doc-viewer#1]
The _Rust (rls)_ extension supports running from an untitled workspace.
But the _Rust: Doc Viewer_ fails with:
> Rust: Docs Viewer: No workspace defined to display docs from, please open a folder in the workspace

![image](https://user-images.githubusercontent.com/5705972/57155273-e1f21380-6d8f-11e9-8c90-bfa30401b0f9.png)

**Comment by JScearcy** [comment]
Excellent find. I'll take a look at handling this case.

**Comment by JScearcy** [comment]
Pushed out a fix for this -> https://marketplace.visualstudio.com/items?itemName=JScearcy.rust-doc-viewer&ssr=false#overview
