### ISSUE TITLE
[BUG] Can't navigate in the docs

### ISSUE THREAD

**Issue by rlnt** [JScearcy/rust-doc-viewer#18]
**Describe the bug**
When I build my docs via `cargo doc` and then open up the preview via the command panel, it loads for a while and then opens up the index page where it shows my crate/project name and my functions.
But if I want to navigate through other crate pages, I simply get an error and nothing happens.
The error can be seen here:
![](https://i.imgur.com/IRk7F7h.png)

I have the default path for the cargo docs.

**To Reproduce**
1. Generate the docs via `cargo doc`
2. Activate the preview in VSCode command palette
3. Wait until the preview loads
4. Try to navigate through other pages.

**Expected behavior**
It should just open the other pages just like the first page without any error.

**Screenshots**
This is how the whole window looks like: https://i.imgur.com/V4zoQAi.png

**Comment by JScearcy** [comment]
I was able to reproduce, I'll be working on a fix for this.

**Comment by JScearcy** [comment]
Please test v2.0.0 - it has been deployed, in my local testing it appears to be resolved.

**Comment by rlnt** [comment]
It resolved the issue mostly but some crates still can't be accessed.

For testing purposes, I used the guessing game example from the Rust guide book.
Crates I can't open the doc pages for are `cfg_if` and `ppv_lite86`.
![](https://i.imgur.com/lRIN32Q.png)

Additionally, it still takes a lot of time to initially show the docs.
It also takes very long if you close the tab and then reopen it.
Edit: I see this is an open issue by yourself right here: https://github.com/JScearcy/rust-doc-viewer/issues/13

Also just a quick side question (I would create a new issue for that if it's possible):
Are you able to integrate the extension into the command line as well?
Since `cargo doc --open` isn't working on WSL and just opens the HTML file in VSCode,
it would be nice to open your extension page instead.

**Comment by JScearcy** [comment]
I see, it looks like any anchor tags that contained a `#` char were ignored. A new version is published to resolve this, I was able to find a suitable example using the rand crate- which then includes `cfg_if`

**Comment by rlnt** [comment]
Just tested the new version, seems to work now. Thanks :)
Keep up the good work!
