### ISSUE TITLE
Can't navigate documentation.

### ISSUE THREAD

**Issue by Merlin1846** [JScearcy/rust-doc-viewer#25]
Clicking on any link even the ones to navigate the documentation will open my browser and attempt to go to the page regardless of if it is uploaded to crates.io

**To Reproduce**
1. Install the extension.
2. Run it.
3. Click on any link for example a function or struct.

**Expected behavior**
To go to the offline documentation in vscode for that function/struct/...etc

Ubuntu 20.04 KDE

It looked like a good idea and I wanted to use it but this makes it unusable for me. And I can always open the index.html manually and not have this problem. I hope it gets fixed this seemed legitimately useful.

**Comment by Merlin1846** [comment]
I would try fixing this but I don't know typescript.

**Comment by JScearcy** [comment]
I'm currently working on wrapping up a rewrite for the plugin to improve performance, debugging/testability. I'll verify and address this bug if needed with that release

**Comment by JScearcy** [comment]
After the 3.0.0 release I tested in Windows, Ubuntu 18.04 (WSL), and Ubuntu 22.04 GNOME and did not reproduce the issue
Re-open if this issue persists
