### ISSUE TITLE
[BUG] Can't click non local links

### ISSUE THREAD

**Issue by Merlin1846** [JScearcy/rust-doc-viewer#28]
If you click on a type, function, trait, etc that is not from the binary/library such as usize or String then it will show an error.

**Steps to reproduce**
1. Install
2. Run
3. Click type not local to crate such as usize or String.

**Expected behavior**
Open the documentation for the type, either in/from the browser or generate it if possible like with std.

**Additional context**
Links to local things should open the crates page while external links should open the web page or do what the rust analyzer does and generate it from the downloaded source. Yes I know this is more complicated than what appears to be a quick fix that you did.

**Comment by JScearcy** [comment]
Ah good catch, that's a case I missed testing.
std/core docs are not generated with `cargo doc` unless imported in the project -- however it is included in `rustup`
I've got a issue open to add config options a path to the std docs is a thought, with a fallback of opening the hosted docs. Doing some testing on this

**Comment by JScearcy** [comment]
- Release 3.0.1 will open the std online docs
- Release 3.0.2 will allow local docs - although this option will require a path to that set of docs, such as the docs rustup includes

**Comment by JScearcy** [comment]
3.0.2 should have addressed this issue completely, reopen if any other issues related to this persist
