### ISSUE TITLE
[BUG] Paths aren't handled correctly on windows

### ISSUE THREAD

**Issue by IceSentry** [JScearcy/rust-doc-viewer#29]
**Describe the bug**
When clicking on any links in the doc viewer I get an error

**To Reproduce**
For me this happens in every repo I use. I run `cargo doc` then I `Ctrl+shift+P` and select the rust doc viewer option. The index page renders correctly, but the errors shows up on any link I click on the page.

**Expected behavior**
There is no error and the viewer shows the selected page

**Screenshots**
![image](https://user-images.githubusercontent.com/8348954/181842499-02ea9352-49ae-4387-be6a-c309e51b81a2.png)

**Additional context**
It looks like the extension is trying to append 2 absolute paths as if the second one was relative and this understandably doesn't work.

**Comment by JScearcy** [comment]
Tested released version 3.0.3 on Windows 11 successfully
