### ISSUE TITLE
[BUG] Broken links in Windows

### ISSUE THREAD

**Issue by starthal** [JScearcy/rust-doc-viewer#32]
**Describe the bug**
I am seeing bad links on v3.0.3 on Windows 10. 
This may be related to #29 .

**To Reproduce**

- Windows 10
- Visual Studio Code 1.70.2
- Rust Doc Viewer 3.0.3

```shell
cargo new --bin foo
cd foo
cargo add serial
cargo doc
```
Open docs with Ctrl-Shift-P

When clicking a module link:
> Rust: Docs Viewer: EISDIR: illegal operation on a directory, read

When clicking an enum link:
> Rust: Docs Viewer: ENOENT: no such file or directory, open 'C:\struct.Error.html'

A module link at the top-left shows me this on hover:
![image](https://user-images.githubusercontent.com/3247950/185640335-9d396532-1145-4070-bc49-6c1653a68a90.png)

**Expected behavior**
All internal links to function normally.

**Comment by JScearcy** [comment]
An unexpected directory when most everything else is a link directly to a file. I will be updating to use a reasonable default file in this case (likely index.html exists in this directory, will need to look into it deeper)

**Comment by JScearcy** [comment]
Added default when a directory is linked, tested fix on Windows as well as Ubuntu. Released in v3.0.4
