### ISSUE TITLE
Theme Selection for Rust Doc Preview Editor

### ISSUE THREAD

**Issue by sammysheep** [JScearcy/rust-doc-viewer#36]
**Is your feature request related to a problem? Please describe.**
I am using Windows 10 and VS Code 1.78.2 and have tried the plugin via WSL2, Windows native, and CentOS + SSH Remote. It all does basically similar things: opens the preview in Dark mode and makes a lot of documentation invisible / unreadable. My editor is in Dark mode, but I am hoping the preview could open in light mode so text will be readable.

**Describe the solution you'd like**
A setting where I can explicitly define the theme or background color for the extension, this would ensure no weird side effects with other configs.

**Describe alternatives you've considered**
I can switch to light mode for everything (my eyes, my eyes), or download a toggle theme extension. It works, and makes clear the preview theme is inheriting from the VS Code main settings.

**Additional context**
That's all, but let me say thank you and not just ask for stuff. This is a really cool project!

**Comment by JScearcy** [comment]
Thanks, I will check into this. I was attempting to repro this problem on WSL2/Win11 but I'm seeing a default to light mode. 

I did uncover some other issues I'll be checking out as well, but would you be able to post a screenshot? That may help me repro the issue

**Comment by sammysheep** [comment]
I decided to try it on a new computer. This time Mac OS 13.3.1 running over SSH and same thing. Then I created a blank Rust project  _locally_ called `testviewer` and just did:
```
cargo new testviewer
cargo doc
# COMMAND + SHIFT + P + Rust Doc Viewer
```

I was surprised to see the same thing happening. See the screenshot:
<img width="2560" alt="Screenshot 2023-05-18 at 8 35 32 AM" src="https://github.com/JScearcy/rust-doc-viewer/assets/820955/2684a4e7-b807-4d34-850b-3874c18cb87b">


This is the VS Code info from today:
>Version: 1.78.1 (Universal)
>Commit: 6a995c4f4cc2ced6e3237749973982e751cb0bf9
>Date: 2023-05-04T09:57:42.343Z
>Electron: 22.5.1
>Chromium: 108.0.5359.215
>Node.js: 16.17.1
>V8: 10.8.168.25-electron.0
>OS: Darwin x64 22.4.0
>Sandboxed: No

As best I can figure it, if you can't reproduce it maybe another extension is interfering with yours.

**Comment by dkrieger** [comment]
I'm also getting this issue on Fedora 38

**Comment by JScearcy** [comment]
Thanks, I'm getting back from a break and looking into it now. There were some changes to the generated docs bundles to handle, I imagine they are related to this issue.

**Comment by JScearcy** [comment]
I have reproduced this issue. It is related to the generated bundles, specifically a new fetching pattern which causes a CSS load failure. Working on a fix now!

**Comment by JScearcy** [comment]
Version 4.0.0 is published, which should resolve this issue

**Comment by sammysheep** [comment]
Thanks for your hard work on this extension!!
