### ISSUE TITLE
[BUG] Interface is missing CSS

### ISSUE THREAD

**Issue by Yuri6037** [JScearcy/rust-doc-viewer#39]
**Describe the bug**

**To Reproduce**
1. Open rust docs on any project

**Expected behavior**
A normal rust doc view like if I run `cargo doc --open`.

**Screenshots**
<img width="1213" alt="image" src="https://github.com/JScearcy/rust-doc-viewer/assets/6407288/e5152af9-9714-4b97-8459-154cd7eaede7">

**Additional context**
<img width="558" alt="image" src="https://github.com/JScearcy/rust-doc-viewer/assets/6407288/2faf7538-460d-48c8-a864-2f4fa9639c39">

**Comment by Yuri6037** [comment]
Workaround:
- `open -a CotEditor ~/.vscode/extensions/jscearcy.rust-doc-viewer-3.0.4/out/extension.js`.
- Add the following line after line 22544: `dataStaticRootPath: "data-static-root-path",`.
- Add the following line after line 22554: `rustDocVarAttributes.dataStaticRootPath,`.
- Save the file.
- Quit CotEditor.
- In vscode, open command palette and search for `reload window` and select `Developer: Reload Window`.
- You can now open back some docs and it'll work.

Hypothesis: The Rust project has probably changed the generation template for docs and included this new `data-static-root-path` key, which is of course not known by this extension.

Note: You could do the procedure using vim or maybe TextEdit, CotEditor is nicer as it comes with syntax highlighting.

Note 2: You should disable updates to this extension to avoid a new update breaking again the view.

EDIT: In order to bring back the search box, you need to comment line 22555 and 22556 (assuming you've already applied the procedure to bring back CSS)

**Comment by JScearcy** [comment]
Ah yeah, this is also related to this issue https://github.com/JScearcy/rust-doc-viewer/issues/36 - in a recent update the docs will dynamically load CSS via `document.write` which will fail unless prefixed with the vscode file url. I am testing updates, this addition will be released with others in the next few days

**Comment by JScearcy** [comment]
Version 4.0.0 is published, which should resolve this issue
