### ISSUE TITLE
[BUG] Can't open docs when custom cargo target directory is used

### ISSUE THREAD

**Issue by kriomant** [JScearcy/rust-doc-viewer#44]
**Describe the bug**
Extension can't find documentation when custom target directory is used.

**To Reproduce**
1. Create `.cargo/config.toml` file in project or home directory:
```
[build]
target-dir = "/Users/kriomant/.cargo/target"
```
2. Build docs: `cargo doc`
3. Call 'Cargo Doc Open' extension command

**Expected behavior**
Documentation is displayed

**Actual behavior**
"run cargo doc to build documents!" error is displayed

**Additional context**
Extension option is enough to work with globally overridden target directory.
You may also use `cargo metadata` to get per-project target directory.

**Comment by JScearcy** [comment]
`4.1.0` is published - this integrates with `cargo metadata` which resolves this issue in my tests using your MRE
