### ISSUE TITLE
[FEATURE] Add option to update environment variables

### ISSUE THREAD

**Issue by hehaoqian** [JScearcy/rust-doc-viewer#48]
**Is your feature request related to a problem? Please describe.**
May project creates a wrapper of `cargo` to do building. 
The wrapper is generated after build, not in the git repository.
The wrapper setups various environment vars for the real `cargo`,
including `RUSTUP_HOME`, and `CARGO_HOME`.

Lacking the support for updating env vars, I have to add the PATH of cargo wrapper in `~/.bash_profile`,
which is inconvenient, because I may have multiple git directories, and each one contains its own wrapper script.
Add option to update env variable would allow me to choose different `cargo` in different folder.

**Describe the solution you'd like**
Add an option in the same way as `rust-analyzer.cargo.extraEnv` (Rust-analyzer > Cargo: Extra Env),
so I can update PATH in order to choose the location of `cargo`

**Describe alternatives you've considered**
Add an option to choose the absolute path to `cargo`. 
This may be okay if this extension does not use other Rust project executables such as `rustc`

**Comment by JScearcy** [comment]
Thanks, I have finished an initial implementation. I'll be testing and releasing support for this in the upcoming days

**Comment by JScearcy** [comment]
4.2.0 release includes this additional configuration
